### ISSUE TITLE
ATM config has incorrect value

### ISSUE THREAD

**Issue by clev98** [spiceywasabi/atm-processor#1]
The ATM config value "enabled" currently has a value of yes, but later code expects it to be an integer. "enabled" should be a 1 for true or a 0 for false. 

https://github.com/spiceywasabi/atm-processor/blob/095be1d55f0fc2772b4cef88e9371c70284f3968/files/etc/config/atm_setup#L2

**Comment by spiceywasabi** [comment]
This is resolved. Thanks!
